database:
  driver: "postgres"
  dbname: "tjiang"
  username: "tjiang"
  password: "password"
  host: "localhost"
  port: "5432"
  max_lifetime: 7200
  max_open_conns: 150
  max_idle_conns: 50

server:
  port: "5000"
  secret: "password"
  mode: "debug"
  schema: "/Users/tjiang/code/playground/echo-apisvr/schemas/device.json"